name: Deploy

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 1.8
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Build with Gradle
      run: ./gradlew deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
